trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: System.Debug
    value: true
  - group: LGV_VAR_DEMO_GROUP
  - name: vXY_DEMO_PRUEBAS_USERNAME
    value: $[variables.XY_DEMO_PRUEBAS_USERNAME]
  - name: vXY_DEMO_PRUEBAS_PASSWORD
    value: $[variables.XY_DEMO_PRUEBAS_PASSWORD]
  - name: vXY_DEMO_PRUEBAS_URL
    value: $[variables.XY_DEMO_PRUEBAS_URL]

stages:
- stage: Security 
  jobs:
  - job: "Xy_Scanner"
    steps:
    - task: Bash@3
      displayName: 'Install xygeni scanner '
      inputs:
        targetType: 'inline'
        script: |
            ls -l
            java -version
            whoami
            pwd 
            echo $(vXY_DEMO_PRUEBAS_USERNAME)
            echo $(vXY_DEMO_PRUEBAS_PASSWORD)
            echo $(vXY_DEMO_PRUEBAS_URL)
    - task: Bash@3
      displayName: 'Scan for issues'
      inputs:
        targetType: 'inline'
        script: |
            pwd
            curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $(vXY_DEMO_PRUEBAS_USERNAME) -p $(vXY_DEMO_PRUEBAS_PASSWORD) -s $(vXY_DEMO_PRUEBAS_URL) -d $(Build.SourcesDirectory)/scanner
            ls -l $(Build.SourcesDirectory)/scanner
            $(Build.SourcesDirectory)/scanner/xygeni scan --upload -n ADO-$(System.TeamProject)-CMD --dir $(Build.SourcesDirectory)/src     
    
    - task: Application security testing@2022
        continueOnError: true
        inputs:
          projectName: $(Build.Repository.Name) 
          enableProxy: false
          enableSastScan: false
          enableDependencyScan: true
          dependencyServerURL: 'CxSCA'
          scaTeam: 'CxServer'
          isEnableScaResolver: true
          pathToScaResolver: $(Build.Repository.LocalPath)
          scaResolverAddParameters: '-s $(Build.Repository.LocalPath) -n kaka3 -r $(Build.Repository.LocalPath) --cxserver http://172.35.1.19 --cxuser admin --cxpassword KsHPJ8JCD5otOLixmMov_ --cxprojectname $(Build.Repository.Name) --sast-result-path $(Build.Repository.LocalPath)/lgv.txt '


 
            