on:
  pull_request:
    branches: [ main ]
env:
  MY_SECRET: ${{ secrets.MY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out PR code
      - uses: actions/checkout@v3
     
      # Run tests over the PR code 0 (success), 1 (error - build failed)
      - name: 'Req #1 : Run test'
        run: |
          echo Running tests..
          chmod +x runtests.sh
          ./runtests.sh  
