# This is a basic workflow to help you get started with Actions

name: Scanner on push 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # Runs Xygeni-Scanner
      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v2.0
        id: Xygeni-Scanner
        with:
        
          # API token. Must be provided, or username/password as alternative.
          token: ${{ secrets.XY_PRO_TOKEN }}
          
          # Base URL of the Xygeni API.# optional, default is https://api.xygeni.io
          xygeni_url: https://api.xygeni.io
          
          # Username (using API token is recommended)
          #username: lmgarciaviejo@gmail.com
          
          # Password (using API token is recommended)
          #password: ")5Yf$35WsK"
          
          # Command to execute by the scanner, optional, default is scan --never-fail -n ${{ github.repository }} -d /app
          command: scan --never-fail -n ${{ github.repository }} -d /app 
